# Build settings
title: "Aras' Game Dev Portfolio"

kramdown:
input: GFM
# theme: jekyll-theme-cayman
layout: default
remote_theme: pages-themes/slate@v0.2.0

plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
